# Blog info
blog_name: xiedacon
slogan: Not the best, just better
url: http://www.xiedacon.com

# Set avatar (Absolute url and relative url)
avatar: https://avatars0.githubusercontent.com/u/14571125?v=4&s=460

# Set favicon
favicon: https://avatars0.githubusercontent.com/u/14571125?v=4&s=460

# For seo
keywords: xieda,xiedacon,后端开发,nodejs,Node.js,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/xiedacon
    target_blank: true #在新页面打开
  - name: About
    url: /about
    target_blank: false

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: false # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: Home

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics: UA-104151244-1
baidu_analytics: be63393720f6228b376be11e9672f592

# Comment service
# disqus_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
# uyan_key:

# 畅言, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  这里开启
  changyan_appid:
  changyan_appkey:

# gitalk评论组件，把下面的配置换成你的，官方文档: https://gitalk.github.io/
gitalk:
  enable: false # 如果使用 gitalk，请设置改之为true
  clientID: 
  clientSecret:
  repo:
  owner:
  admin:


# gitment comment service
gitment:
  enable: false  # true | false  这里开启
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "1995/3/18"
    - "Talk is cheep, show me the code"
    - "Noder"
  - type: resume
    icon: icon-resume
    text_key: 简历
    text_value: "@xiedacon"
    text_value_url: https://xiedacon.github.io/resume/
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@xiedacon"
    text_value_url: https://github.com/xiedacon
  - type: Cnode
    icon: icon-cnode
    text_key: Cnode
    text_value: "@xiedacon"
    text_value_url: https://cnodejs.org/user/xiedacon
  - type: 简书
    icon: icon-jianshu
    text_key: 简书
    text_value: "@xiedacon"
    text_value_url: http://www.jianshu.com/u/c241dafeb640
  - type: Segmentfault
    icon: icon-segmentfault
    text_key: Segmentfault
    text_value: "@xiedacon"
    text_value_url: https://segmentfault.com/u/xiedacon
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "xiedacon@qq.com"
    text_value_url: mailto::xiedacon@qq.com
  - type: location
    icon: icon-location
    text_value: 武汉

project:
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: spider-trending
    url: https://github.com/xiedacon/spider-trending
    intro: A spider for github trending
  - type: personal
    name: nodeclub-koa
    url: https://github.com/xiedacon/nodeclub-koa
    intro: Use koa to rewrite nodeclub
  - type: personal
    name: music
    url: https://github.com/xiedacon/music
    intro: A music website build with java
  - type: personal
    name: generate
    url: https://github.com/xiedacon/generate
    intro: Generate your repositories
  - type: personal
    name: small-server
    url: https://github.com/xiedacon/small-server
    intro: 一个简单的静态资源服务器实现，可以使用在任何目录