# Blog info
blog_name: xiedacon
slogan: 
url: http://www.xiedacon.com

# Set avatar (Absolute url and relative url)
avatar: https://avatars0.githubusercontent.com/u/14571125?v=4&s=460

# Set favicon
favicon: https://avatars0.githubusercontent.com/u/14571125?v=4&s=460

# For seo
keywords: xiedacon,后端开发,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/xiedacon
    target_blank: true #在新页面打开

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: false # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: Home

search_slogan:
  isShow: false # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 forsigner@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics: UA-104151244-1
baidu_analytics: be63393720f6228b376be11e9672f592

# Comment service
disqus_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# 注意，多说即将关闭，建议选用上面四个评论系统
# duoshuo_shortname: forsigner

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "1995/3/18"
    - "Talk is cheep, show me the code"
    - "Noder"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@xiedacon"
    text_value_url: https://github.com/xiedacon
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "xiedacon@qq.com"
    text_value_url: mailto::xiedacon@qq.com
  - type: location
    icon: icon-location
    text_value: 武汉

project:
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: spider-trending
    url: https://github.com/xiedacon/spider-trending
    intro: A spider for github trending
  - type: personal
    name: nodeclub-koa
    url: https://github.com/xiedacon/nodeclub-koa
    intro: Use koa to rewrite nodeclub
  - type: personal
    name: music
    url: https://github.com/xiedacon/music
    intro: A music website build with java